# Generated by Django 5.2.8 on 2025-11-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('products_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('batch_create', 'Batch Created'), ('batch_update', 'Batch Updated'), ('movement_record', 'Movement Recorded'), ('stock_adjust', 'Stock Adjusted'), ('batch_expire', 'Batch Expired'), ('physical_count', 'Physical Count')], db_index=True, max_length=50)),
                ('product_id', models.IntegerField()),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_id', 'created_at'], name='inventory_i_product_1c3a6e_idx'), models.Index(fields=['batch_id', 'created_at'], name='inventory_i_batch_i_d6b5f4_idx'), models.Index(fields=['operation_type', 'created_at'], name='inventory_i_operati_80e7e2_idx')],
            },
        ),
    ]
