# Generated by Django 5.2.8 on 2025-11-22 05:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('company_code', models.CharField(max_length=50, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=63)),
                ('financial_year_start_month', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('established_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_code'], name='common_comp_company_75ffa4_idx'), models.Index(fields=['tax_id'], name='common_comp_tax_id_7e559b_idx'), models.Index(fields=['is_active'], name='common_comp_is_acti_851e86_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('financial_year_start_month__gte', 1), ('financial_year_start_month__lte', 12)), name='valid_fy_start_month')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('notification_types', models.JSONField(default=dict, help_text='Dict mapping notification types to enabled status')),
                ('daily_digest', models.BooleanField(default=False)),
                ('digest_time', models.TimeField(default='09:00:00')),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default='22:00:00')),
                ('quiet_hours_end', models.TimeField(default='07:00:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('invoice_number_format', models.CharField(default='{PREFIX}-{YEAR}{MONTH}-{SEQUENCE}', help_text='Format: {PREFIX}, {YEAR}, {MONTH}, {SEQUENCE}, {DAY}', max_length=50)),
                ('next_invoice_sequence', models.IntegerField(default=1000)),
                ('po_prefix', models.CharField(default='PO', max_length=20)),
                ('po_number_format', models.CharField(default='{PREFIX}-{YEAR}-{SEQUENCE}', help_text='Format: {PREFIX}, {YEAR}, {SEQUENCE}', max_length=50)),
                ('next_po_sequence', models.IntegerField(default=100)),
                ('grn_prefix', models.CharField(default='GRN', max_length=20)),
                ('grn_number_format', models.CharField(default='{PREFIX}-{YEAR}-{SEQUENCE}', help_text='Format: {PREFIX}, {YEAR}, {SEQUENCE}', max_length=50)),
                ('next_grn_sequence', models.IntegerField(default=500)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('tax_enabled', models.BooleanField(default=True)),
                ('low_stock_threshold', models.IntegerField(default=50)),
                ('reorder_point', models.IntegerField(default=100)),
                ('payment_grace_period_days', models.IntegerField(default=0)),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('smtp_server', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254)),
                ('api_rate_limit_enabled', models.BooleanField(default=True)),
                ('api_rate_limit_requests', models.IntegerField(default=100)),
                ('api_rate_limit_period_minutes', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('retrieve', 'Retrieve'), ('login', 'Login'), ('logout', 'Logout'), ('permission_change', 'Permission Change'), ('config_change', 'Configuration Change')], max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='common_audi_action__c2c682_idx'), models.Index(fields=['entity_type', 'entity_id'], name='common_audi_entity__e0ef87_idx'), models.Index(fields=['user', 'created_at'], name='common_audi_user_id_721175_idx'), models.Index(fields=['created_at'], name='common_audi_created_bca81d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('order_shipped', 'Order Shipped'), ('payment_received', 'Payment Received'), ('payment_overdue', 'Payment Overdue'), ('inventory_low', 'Low Inventory Alert'), ('purchase_approved', 'Purchase Order Approved'), ('receipt_created', 'Goods Receipt Created'), ('user_welcome', 'User Welcome'), ('password_reset', 'Password Reset'), ('custom', 'Custom Template')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('variables', models.JSONField(default=list, help_text='List of supported variables: {{order_number}}, {{customer_name}}, {{amount}}, {{date}}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_type', 'template_name'],
                'indexes': [models.Index(fields=['template_type'], name='common_emai_templat_335156_idx'), models.Index(fields=['is_active'], name='common_emai_is_acti_c179d7_idx')],
            },
        ),
    ]
