# Generated by Django 5.2.8 on 2025-12-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='billing_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Prefix, numbering, due days, payment modes'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='discount_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Enable discounts, limits, approval'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='invoice_appearance',
            field=models.JSONField(blank=True, default=dict, help_text='Theme, footer, terms'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='loyalty_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Points logic, expiry, redemption'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Alert toggles'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='report_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Access control for reports'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='security_settings',
            field=models.JSONField(blank=True, default=dict, help_text='2FA, timeouts'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tax_settings',
            field=models.JSONField(blank=True, default=dict, help_text='GST enabled, rates, types'),
        ),
    ]
