# Generated by Django 5.2.8 on 2025-12-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_companyprofile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
