# Generated by Django 5.2.8 on 2025-11-22 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['code'], name='users_permi_code_cba410_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='users_role_name_dbf39a_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'created_at'], name='users_userr_user_id_e4c38b_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'created_at'], name='users_userr_role_id_2cee80_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role'),
        ),
    ]
