# Generated by Django 5.2.8 on 2025-11-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='otp',
            name='unique_active_otp',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='attempts',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', 'used'], name='auth_app_ot_phone_f6be78_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='auth_app_ot_expires_8220dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='otp',
            constraint=models.UniqueConstraint(condition=models.Q(('used', False)), fields=('phone', 'code', 'used'), name='unique_active_otp'),
        ),
    ]
