# Generated by Django 5.2.8 on 2025-12-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_otp_unique_active_otp_remove_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
