# Generated by Django 5.2.8 on 2025-12-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_user_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('service', 'Service'), ('grocery', 'Grocery')], help_text='Type of business', max_length=20, null=True),
        ),
    ]
