# Generated by Django 5.2.8 on 2026-01-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_user_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salesman_id',
            field=models.CharField(blank=True, help_text='Auto-generated ID for Sales Executives (e.g. SE-1001)', max_length=20, null=True, unique=True),
        ),
    ]
