# Generated by Django 5.2.8 on 2026-01-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_user_salesman_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salesman_id',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated ID for Sales Executives (e.g. SE-1001)', max_length=20, null=True),
        ),
    ]
