# Generated by Django 5.2.8 on 2025-12-19 15:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Unique code for the discount (e.g., SUMMER10)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('applies_to', models.CharField(choices=[('item', 'Specific Item'), ('bill', 'Total Bill')], default='bill', max_length=20)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum bill amount required', max_digits=12)),
                ('max_discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage type)', max_digits=12, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False, help_text='If true, requires owner approval for sales executives')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_discounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_discount_logs', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_discounts', to='billing.invoice')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='billing.discountrule')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['code'], name='billing_dis_code_37414e_idx'),
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['valid_from', 'valid_to'], name='billing_dis_valid_f_30b6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['is_active'], name='billing_dis_is_acti_9642d5_idx'),
        ),
    ]
