# Generated by Django 5.2.8 on 2026-01-02 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_company_details_invoice_owner'),
        ('customer', '0007_alter_customer_gstin_alter_customer_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discountrule',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='code',
            field=models.CharField(help_text='Unique code for the discount (e.g., SUMMER10)', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='discountrule',
            constraint=models.UniqueConstraint(fields=('code', 'owner'), name='unique_discount_code_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('invoice_number', 'owner'), name='unique_invoice_number_per_owner'),
        ),
    ]
