# Generated by Django 5.2.8 on 2025-12-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_staff_users',
            field=models.IntegerField(default=1, help_text='Maximum number of Sales Executives/staff users (0 = unlimited)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(choices=[('FREE', 'Free Trial'), ('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('CUSTOM', 'Custom Plan')], max_length=20, unique=True),
        ),
    ]
