# Generated by Django 5.2.8 on 2025-12-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionplan_max_staff_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
