# Generated by Django 5.2.8 on 2025-12-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_usersubscription_payment_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
