# Generated by Django 5.2.8 on 2025-12-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscriptionplan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='branch_limit',
            field=models.CharField(default='1', help_text="e.g. '1', 'Unlimited'", max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='business_limit',
            field=models.CharField(default='1', help_text="e.g. '1', 'Multiple'", max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='invoice_limit',
            field=models.CharField(default='100', help_text="e.g. '100', '1000', 'Unlimited'", max_length=50),
        ),
    ]
