# Generated by Django 5.2.8 on 2026-01-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscriptionplan_branch_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='customer_limit',
            field=models.CharField(default='Unlimited', help_text="e.g. '20', 'Unlimited'", max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='product_limit',
            field=models.CharField(default='Unlimited', help_text="e.g. '20', '200', 'Unlimited'", max_length=50),
        ),
    ]
