# Generated by Django 5.2.8 on 2026-01-09 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_preferred_supplier_product_reorder_quantity'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(default='low_stock', max_length=50)),
                ('sent_via', models.CharField(default='simulated', max_length=20)),
                ('status', models.CharField(default='success', max_length=20)),
                ('message_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_notifications', to='product.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='purchase.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['supplier', 'created_at'], name='purchase_su_supplie_7b00c1_idx')],
            },
        ),
    ]
