# Generated by Django 5.2.8 on 2026-01-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_supplier_owner_alter_supplier_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
