# Generated by Django 5.2.8 on 2025-12-10 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
