# Generated by Django 5.2.8 on 2025-12-12 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{7,20}$', 'Phone must contain at least 7 digits')]),
        ),
    ]
