# Generated by Django 5.2.8 on 2025-12-16 08:51

import apps.customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_rupee', models.DecimalField(decimal_places=2, default=1.0, help_text='How many points earned per 1 Rupee spent', max_digits=5)),
                ('redeem_value', models.DecimalField(decimal_places=2, default=0.1, help_text='Value of 1 point in Rupees (e.g. 0.10 means 10 points = ₹1)', max_digits=5)),
                ('bronze_threshold', models.IntegerField(default=0)),
                ('silver_threshold', models.IntegerField(default=1000)),
                ('gold_threshold', models.IntegerField(default=3000)),
                ('platinum_threshold', models.IntegerField(default=5000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Settings',
                'verbose_name_plural': 'Loyalty Settings',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='joined_date',
            field=models.DateField(default=apps.customer.models.get_today),
        ),
    ]
