# Generated by Django 5.2.8 on 2025-12-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_loyaltysettings_alter_customer_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uses_gst',
            field=models.BooleanField(default=True, help_text="Whether GST applies to this customer's invoices"),
        ),
    ]
