# Generated by Django 5.2.8 on 2026-01-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customer_gstin_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, help_text='Auto-generated ID for Customers (e.g. CUS-1001)', max_length=20, null=True, unique=True),
        ),
    ]
