# Generated by Django 5.2.8 on 2025-11-22 05:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('reference_purchase_id', models.IntegerField(blank=True, null=True)),
                ('received_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('remaining_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('purchase', 'Purchase Receipt'), ('sale', 'Sale'), ('adjustment', 'Inventory Adjustment'), ('damage', 'Damage/Loss'), ('return', 'Customer Return'), ('transfer', 'Transfer')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'created_at'], name='product_cat_is_acti_a3e89d_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_non_negative'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='product.product'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='product.inventorybatch'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='product.product'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['product', 'remaining_quantity'], name='product_inv_product_019ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['expiry_date'], name='product_inv_expiry__14b057_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['batch_number'], name='product_inv_batch_n_b446b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__lte', models.F('received_quantity'))), name='remaining_lte_received'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__gte', 0)), name='remaining_non_negative'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'created_at'], name='product_inv_product_66d684_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['change_type', 'created_at'], name='product_inv_change__cc5845_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['reference_id', 'reference_type'], name='product_inv_referen_2ff9d3_idx'),
        ),
    ]
