# Generated by Django 5.2.8 on 2025-12-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_tax_rate_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#3B82F6', max_length=7, null=True),
        ),
    ]
