# Generated by Django 5.2.8 on 2026-01-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Piece', 'Piece'), ('Kg', 'Kg'), ('Litre', 'Litre'), ('Box', 'Box'), ('Meter', 'Meter')], default='Piece', max_length=20),
        ),
    ]
