# Generated by Django 5.2.8 on 2025-12-15 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_data_export',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_owner_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_backup_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_block_on_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_reset_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('NEVER', 'Never')], default='YEARLY', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='backup_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cgst_sgst_enabled',
            field=models.BooleanField(default=True, help_text='For intra-state'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='data_retention_days',
            field=models.IntegerField(default=730, help_text='Days to retain data (0 = indefinite)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_plan_after_trial',
            field=models.CharField(default='FREE', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_theme',
            field=models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark')], default='DARK', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_trial_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_gst_tax',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_invoice_pdf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_loyalty_points',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_pos_billing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_sms_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_stock_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='grace_period_days',
            field=models.IntegerField(default=3, help_text='Days after expiry before blocking'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gst_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='igst_enabled',
            field=models.BooleanField(default=True, help_text='For inter-state'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='invite_only_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='invoice_prefix',
            field=models.CharField(default='INV', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='invoice_starting_number',
            field=models.IntegerField(default=1001),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_login_attempts',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_min_length',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_require_numbers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_require_special_chars',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_require_uppercase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='platform_name',
            field=models.CharField(default='Billing Application', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='primary_color',
            field=models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='require_email_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='require_phone_otp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='separate_pos_series',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='session_timeout_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tax_mode',
            field=models.CharField(choices=[('INCLUSIVE', 'Inclusive (Price includes tax)'), ('EXCLUSIVE', 'Exclusive (Tax added to price)')], default='EXCLUSIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='company_name',
            field=models.CharField(default='Your Company', max_length=255),
        ),
    ]
