# Generated by Django 5.2.8 on 2025-12-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_systemsettings_allow_data_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_flat_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_percent_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='discount_tax_config',
            field=models.CharField(choices=[('BEFORE_TAX', 'Before Tax'), ('AFTER_TAX', 'After Tax')], default='BEFORE_TAX', help_text='Global rule for discount application order', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_discounts',
            field=models.BooleanField(default=True, help_text='Global switch for discount module'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_discount_amount',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Global limit for flat discounts', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Global limit for percentage discounts', max_digits=5),
        ),
    ]
