# Generated by Django 5.2.8 on 2025-12-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_systemsettings_allow_flat_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allowed_discount_level',
            field=models.CharField(choices=[('ITEM_ONLY', 'Item Level Only'), ('BILL_ONLY', 'Bill Level Only'), ('BOTH', 'Both Item & Bill Level')], default='BOTH', help_text='Global rule for where discounts can be applied', max_length=20),
        ),
    ]
