# Generated by Django 5.2.8 on 2025-12-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0004_systemsettings_allowed_discount_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_access_enable',
            field=models.BooleanField(default=True, help_text='Enable/Disable owner dashboard completely'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_active_customers_card',
            field=models.BooleanField(default=True, help_text='Show Active Customers card'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_add_customer_button',
            field=models.BooleanField(default=True, help_text='Show Add Customer button'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_add_product_button',
            field=models.BooleanField(default=True, help_text='Show Add Product button'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_create_invoice_button',
            field=models.BooleanField(default=True, help_text='Show Create Invoice button'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_data_calculation_enable',
            field=models.BooleanField(default=True, help_text='Calculate and show dashboard numbers (safe mode if disabled)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_invoice_number_visibility',
            field=models.BooleanField(default=True, help_text='Show Invoice numbers in orders'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_notification_bell',
            field=models.BooleanField(default=True, help_text='Show notification bell for alerts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_order_amount_visibility',
            field=models.BooleanField(default=True, help_text='Show order amounts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_order_status_visibility',
            field=models.BooleanField(default=True, help_text='Show order status'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_recent_orders_widget',
            field=models.BooleanField(default=True, help_text='Show Recent Orders section'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_revenue_visibility',
            field=models.BooleanField(default=True, help_text='Show revenue amounts (prevents showing ₹ for trial/restricted)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_total_customers_card',
            field=models.BooleanField(default=True, help_text='Show Total Customers card'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_total_products_card',
            field=models.BooleanField(default=True, help_text='Show Total Products card'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_total_revenue_card',
            field=models.BooleanField(default=True, help_text='Show Total Revenue card'),
        ),
    ]
