# Generated by Django 5.2.8 on 2025-12-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='level',
            field=models.CharField(choices=[('owner', 'Owner'), ('super_admin', 'Super Admin')], default='owner', max_length=20),
        ),
    ]
